---
title: "Data Type"
format: html
---

## Atomic Data Types

Single value

```{r}
print_info <- function(var) {
  print(paste(" value:", var))
  print(paste(" class:", class(var)))  # user-facing, high-level classification
  print(paste("typeof:", typeof(var))) # internal, low-level storage mode
  print(str(var))                      # compact summary of the internal structure
}
```


```{r}
# logical
l = TRUE
print_info(l)
```

```{r}
# integer
i = 10L
print_info(i)
```

```{r}
# numeric
n = 10
print_info(n)
```

```{r}
# character
c = "10"
print_info(c)
```



## Structure Data Types

Multiple values

### Vectors

1+ items, same atomic data type

```{r}
# create empty vector then fill it with values
v = vector("integer", length = 3)
v[1] = 10
v[2] = 20
v[3] = 30
print_info(v)

# create vector directly
v2 = c(40, 50, 60)
print_info(v2)
```

### Lists

1+ items, can be mixed of diff. atomic data types and diff structuredata types

```{r}
lst = list(FALSE, 10L, 20, "30")
print_info(lst)

lst2 = list(c(FALSE, FALSE), list(c(10L, 11L)), 20, 30)
print_info(lst2)
```

### Naming

Giving names to elements

```{r}
# unnamed vector
v2 = c(40, 50, 60)
print_info(v2)
v2[1]

# named vector
v2n = c(e1 = 40, e2 = 50, e3 = 60)
print_info(v2n)
v2n[1]
v2n["e1"]
```

```{r}
# unnamed list
lst2 = list(c(FALSE, FALSE), list(c(10L, 11L)), 20, 30)
print_info(lst2)
lst2[1]
lst2[[1]]

# named list
lst2n = list(e1 = c(FALSE, FALSE), e2 = list(c(10L, 11L)), e3 = 20, e4 = 30)
print_info(lst2n)
lst2n[1]
lst2n["e1"]
```

### Data Frames

Named list, each element is a vector of same length that can be of different types

```{r}
df = data.frame(e1 = c(1L, 2L), e2 = c("aa", "bb"))
print_info(df)
df["e1"]
df[1]
df[[1]]
```

```{r}
#| eval: false

df2 = data.frame(e1 = c(1L, 2L, 3L), e2 = c("aa", "bb"))
```


### `[]` vs `[[]]`

```{r}
df = data.frame(e1 = c(1L, 2L), e2 = c("aa", "bb"))
df["e1"] |> class()
df[["e1"]] |> class()
```

